"""add edit_mode and edit_target to interview sessions

Revision ID: 4e7fcfe90ba9
Revises: d67b6e8238d4
Create Date: 2026-05-26 00:23:54.955104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e7fcfe90ba9'
down_revision: Union[str, None] = 'd67b6e8238d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edit_mode', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('edit_target', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_sessions', schema=None) as batch_op:
        batch_op.drop_column('edit_target')
        batch_op.drop_column('edit_mode')

    # ### end Alembic commands ###
