"""initial schema — all 16 tables

Revision ID: 50f6aeda4e74
Revises: 
Create Date: 2026-05-18 07:48:35.702457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50f6aeda4e74'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('financial_year', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('background_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_background_jobs_workspace_id'), 'background_jobs', ['workspace_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('financial_year', sa.String(length=10), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('extraction_method', sa.String(length=30), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('extracted_fields', sa.JSON(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('skill_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('archived_reason', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_sha256_hash'), 'documents', ['sha256_hash'], unique=False)
    op.create_index(op.f('ix_documents_workspace_id'), 'documents', ['workspace_id'], unique=False)
    op.create_table('encrypted_drafts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('form_type', sa.String(length=30), nullable=False),
    sa.Column('encrypted_content', sa.Text(), nullable=True),
    sa.Column('last_saved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encrypted_drafts_workspace_id'), 'encrypted_drafts', ['workspace_id'], unique=False)
    op.create_table('export_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('financial_year', sa.String(length=10), nullable=False),
    sa.Column('readiness_pct', sa.Float(), nullable=True),
    sa.Column('confirmed_count', sa.Integer(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('agent_count', sa.Integer(), nullable=False),
    sa.Column('missing_count', sa.Integer(), nullable=False),
    sa.Column('skills_active', sa.JSON(), nullable=True),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_records_workspace_id'), 'export_records', ['workspace_id'], unique=False)
    op.create_table('feature_flags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('feature', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_flags_workspace_id'), 'feature_flags', ['workspace_id'], unique=False)
    op.create_table('interview_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('financial_year', sa.String(length=10), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('current_step', sa.JSON(), nullable=True),
    sa.Column('completed_steps', sa.JSON(), nullable=True),
    sa.Column('skipped_steps', sa.JSON(), nullable=True),
    sa.Column('branch_path', sa.JSON(), nullable=True),
    sa.Column('pending_queue', sa.JSON(), nullable=True),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.Column('activated_skills', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_sessions_workspace_id'), 'interview_sessions', ['workspace_id'], unique=False)
    op.create_table('readiness_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('financial_year', sa.String(length=10), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=True),
    sa.Column('missing_items', sa.JSON(), nullable=True),
    sa.Column('review_items', sa.JSON(), nullable=True),
    sa.Column('agent_items', sa.JSON(), nullable=True),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_readiness_scores_workspace_id'), 'readiness_scores', ['workspace_id'], unique=False)
    op.create_table('skill_version_locks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=50), nullable=False),
    sa.Column('skill_version', sa.String(length=20), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_version_locks_workspace_id'), 'skill_version_locks', ['workspace_id'], unique=False)
    op.create_table('tax_deadline_reminders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('financial_year', sa.String(length=10), nullable=False),
    sa.Column('deadline_type', sa.String(length=20), nullable=False),
    sa.Column('deadline_date', sa.String(length=10), nullable=False),
    sa.Column('reminders', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_deadline_reminders_workspace_id'), 'tax_deadline_reminders', ['workspace_id'], unique=False)
    op.create_table('tax_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('financial_year', sa.String(length=10), nullable=False),
    sa.Column('employment_type', sa.String(length=20), nullable=True),
    sa.Column('resident_status', sa.String(length=20), nullable=True),
    sa.Column('user_lodger_type', sa.String(length=20), nullable=True),
    sa.Column('has_wfh', sa.Boolean(), nullable=False),
    sa.Column('has_investments', sa.Boolean(), nullable=False),
    sa.Column('has_crypto', sa.Boolean(), nullable=False),
    sa.Column('has_property', sa.Boolean(), nullable=False),
    sa.Column('has_private_health', sa.Boolean(), nullable=False),
    sa.Column('has_sole_trader', sa.Boolean(), nullable=False),
    sa.Column('has_spouse', sa.Boolean(), nullable=False),
    sa.Column('has_dependents', sa.Boolean(), nullable=False),
    sa.Column('spouse_income_range', sa.String(length=30), nullable=True),
    sa.Column('dependent_count', sa.Integer(), nullable=False),
    sa.Column('has_novated_lease', sa.Boolean(), nullable=False),
    sa.Column('spouse_has_novated_lease', sa.Boolean(), nullable=False),
    sa.Column('spouse_rfba_amount', sa.Float(), nullable=True),
    sa.Column('active_skills', sa.JSON(), nullable=True),
    sa.Column('fy_end_reminder_set', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_profiles_workspace_id'), 'tax_profiles', ['workspace_id'], unique=False)
    op.create_table('workspace_security',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('password_encrypted_dek', sa.Text(), nullable=True),
    sa.Column('recovery_key_hash', sa.String(length=255), nullable=True),
    sa.Column('recovery_encrypted_dek', sa.Text(), nullable=True),
    sa.Column('unlock_session_token', sa.String(length=255), nullable=True),
    sa.Column('unlock_session_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_security_workspace_id'), 'workspace_security', ['workspace_id'], unique=False)
    op.create_table('yoy_suggestions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('source_workspace_id', sa.String(length=36), nullable=True),
    sa.Column('financial_year', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount_last_year', sa.Float(), nullable=True),
    sa.Column('frequency', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('shown_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_yoy_suggestions_workspace_id'), 'yoy_suggestions', ['workspace_id'], unique=False)
    op.create_table('tax_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('financial_year', sa.String(length=10), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('ai_reasoning', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('review_status', sa.String(length=30), nullable=False),
    sa.Column('possible_duplicate', sa.Boolean(), nullable=False),
    sa.Column('user_action', sa.String(length=30), nullable=True),
    sa.Column('user_note', sa.Text(), nullable=True),
    sa.Column('amended_amount', sa.Float(), nullable=True),
    sa.Column('amended_category', sa.String(length=100), nullable=True),
    sa.Column('skill_id', sa.String(length=50), nullable=True),
    sa.Column('skill_version', sa.String(length=20), nullable=True),
    sa.Column('group_id', sa.String(length=36), nullable=True),
    sa.Column('group_display', sa.String(length=255), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurrence_index', sa.Integer(), nullable=True),
    sa.Column('correction_history', sa.JSON(), nullable=True),
    sa.Column('inline_answers', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_events_document_id'), 'tax_events', ['document_id'], unique=False)
    op.create_index(op.f('ix_tax_events_group_id'), 'tax_events', ['group_id'], unique=False)
    op.create_index(op.f('ix_tax_events_workspace_id'), 'tax_events', ['workspace_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('tax_event_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('actor', sa.String(length=20), nullable=False),
    sa.Column('field', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('ai_operation', sa.String(length=30), nullable=True),
    sa.Column('ai_provider', sa.String(length=30), nullable=True),
    sa.Column('ai_model', sa.String(length=50), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('ai_success', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tax_event_id'], ['tax_events.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_tax_event_id'), 'audit_logs', ['tax_event_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_workspace_id'), 'audit_logs', ['workspace_id'], unique=False)
    op.create_table('review_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('tax_event_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('date', sa.String(length=10), nullable=True),
    sa.Column('skill_id', sa.String(length=50), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('ai_reasoning', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('inline_questions', sa.JSON(), nullable=True),
    sa.Column('inline_answers', sa.JSON(), nullable=True),
    sa.Column('questions_complete', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('user_action', sa.String(length=30), nullable=True),
    sa.Column('user_note', sa.Text(), nullable=True),
    sa.Column('amended_amount', sa.Float(), nullable=True),
    sa.Column('amended_category', sa.String(length=100), nullable=True),
    sa.Column('skipped_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_duration_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tax_event_id'], ['tax_events.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_items_tax_event_id'), 'review_items', ['tax_event_id'], unique=False)
    op.create_index(op.f('ix_review_items_workspace_id'), 'review_items', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_items_workspace_id'), table_name='review_items')
    op.drop_index(op.f('ix_review_items_tax_event_id'), table_name='review_items')
    op.drop_table('review_items')
    op.drop_index(op.f('ix_audit_logs_workspace_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tax_event_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_tax_events_workspace_id'), table_name='tax_events')
    op.drop_index(op.f('ix_tax_events_group_id'), table_name='tax_events')
    op.drop_index(op.f('ix_tax_events_document_id'), table_name='tax_events')
    op.drop_table('tax_events')
    op.drop_index(op.f('ix_yoy_suggestions_workspace_id'), table_name='yoy_suggestions')
    op.drop_table('yoy_suggestions')
    op.drop_index(op.f('ix_workspace_security_workspace_id'), table_name='workspace_security')
    op.drop_table('workspace_security')
    op.drop_index(op.f('ix_tax_profiles_workspace_id'), table_name='tax_profiles')
    op.drop_table('tax_profiles')
    op.drop_index(op.f('ix_tax_deadline_reminders_workspace_id'), table_name='tax_deadline_reminders')
    op.drop_table('tax_deadline_reminders')
    op.drop_index(op.f('ix_skill_version_locks_workspace_id'), table_name='skill_version_locks')
    op.drop_table('skill_version_locks')
    op.drop_index(op.f('ix_readiness_scores_workspace_id'), table_name='readiness_scores')
    op.drop_table('readiness_scores')
    op.drop_index(op.f('ix_interview_sessions_workspace_id'), table_name='interview_sessions')
    op.drop_table('interview_sessions')
    op.drop_index(op.f('ix_feature_flags_workspace_id'), table_name='feature_flags')
    op.drop_table('feature_flags')
    op.drop_index(op.f('ix_export_records_workspace_id'), table_name='export_records')
    op.drop_table('export_records')
    op.drop_index(op.f('ix_encrypted_drafts_workspace_id'), table_name='encrypted_drafts')
    op.drop_table('encrypted_drafts')
    op.drop_index(op.f('ix_documents_workspace_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_sha256_hash'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_background_jobs_workspace_id'), table_name='background_jobs')
    op.drop_table('background_jobs')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
