"""add setup_confirmed to workspace_security

Revision ID: 83f4fa014c1b
Revises: 50f6aeda4e74
Create Date: 2026-05-19 03:12:27.907073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83f4fa014c1b'
down_revision: Union[str, None] = '50f6aeda4e74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace_security', schema=None) as batch_op:
        batch_op.add_column(sa.Column('setup_confirmed', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('recovery_confirm_hash', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace_security', schema=None) as batch_op:
        batch_op.drop_column('recovery_confirm_hash')
        batch_op.drop_column('setup_confirmed')

    # ### end Alembic commands ###
