"""add event_metadata column to tax_events

Revision ID: d67b6e8238d4
Revises: 83f4fa014c1b
Create Date: 2026-05-24 06:46:51.342772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd67b6e8238d4'
down_revision: Union[str, None] = '83f4fa014c1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tax_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_metadata', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tax_events', schema=None) as batch_op:
        batch_op.drop_column('event_metadata')

    # ### end Alembic commands ###
